algoritmo "nomedoproduto"
// Função :
// Autor :
// Data : 04/05/2020
// Seção de Declarações 
var
nome: caracter
result, preco: real
inicio
// Entrada
escreval ("Qual é o nome do produto?")
leia (nome)


escreval ("Qual é o preço produto?")
leia (preco)

// Processamento

result<- preco*1.65

// Saída

escreval ("Por quanto você pode vender a ",nome," por R$", result)
fimalgoritmo
